name: Fortran

on:
  push:
    branches: 
    - main
    paths:
      - '.github/workflows/fortran.yml'
      - 'enzyme/Enzyme/**'
      - 'enzyme/Fortran/**'
      - 'enzyme/includes/**'
      - 'enzyme/test/**'
      - 'enzyme/tools/**'
      - 'enzyme/benchmarks/**'
      - 'enzyme/cmake/**'
      - 'enzyme/CMakeLists.txt'
      - 'enzyme/CMakePresets.json'
  pull_request:
    # TODO: TEMPORARY
    # branches: 
    # - main
    paths:
      - '.github/workflows/fortran.yml'
      - 'enzyme/Enzyme/**'
      - 'enzyme/Fortran/**'
      - 'enzyme/includes/**'
      - 'enzyme/test/**'
      - 'enzyme/tools/**'
      - 'enzyme/benchmarks/**'
      - 'enzyme/cmake/**'
      - 'enzyme/CMakeLists.txt'
      - 'enzyme/CMakePresets.json'
  merge_group:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    
jobs:
  build-and-test-fortran:
    name: Fortran ${{matrix.build}} ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        build: ["Release", "Debug"]
        os: [ubuntu-22.04]
        llvm: [20]
        include:
          - llvm: 20
    timeout-minutes: 60
    steps:
    - name: add llvm
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/`lsb_release -c | cut -f2`/ llvm-toolchain-`lsb_release -c | cut -f2`-${{ matrix.llvm }} main"
        sudo apt-get update && sudo apt-get install -y cmake gcc g++ llvm-${{ matrix.llvm }}-dev ninja-build pip clang-${{ matrix.llvm }} flang-${{ matrix.llvm }}
        sudo python3 -m pip install --upgrade pip lit
        which flang-${{ matrix.llvm }}
    - uses: actions/checkout@v4
    - name: generate build system
      run: |
        rm -rf build && mkdir build && cd build
        cmake ../enzyme -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DLLVM_DIR=/usr/lib/llvm-${{ matrix.llvm }}/lib/cmake/llvm -DLLVM_EXTERNAL_LIT=`which lit` -DENZYME_FORTRAN=ON -DCMAKE_Fortran_COMPILER=flang-${{ matrix.llvm }}
    - name: build enzyme
      working-directory: 'build'
      run: ninja LLVMEnzyme-${{ matrix.llvm }}
    - name: run Fortran tests
      working-directory: 'build'
      run: ninja check-enzyme-fortran
        
